### ISSUE TITLE
ARM images

### ISSUE THREAD

**Issue by copiltembel** [google/android-emulator-container-scripts#192] opened 2020-08-26 12:02 UTC
@pokowaka : I know that this doesn't really belong here, but I couldn't find any other place to ask for help.

I'd like to run an ARM64 Android System image in the emulator on an ARM64 host. Since Emulator version 30.0.26 we can build the [emulator for ARM64 hosts](https://developer.android.com/studio/releases/emulator#emulator_for_arm64_hosts). I have such a host but the newest ARM64 image for android emulator that I could get my hands on is Nougat (API 25). 

I've tried building my own from AOSP, but it didn't start.

Any hints are welcome!

**Comment by averyzhong** [comment] 2020-09-08 03:30
Have you solved this problem? I also want to run the emulator on the ARM server. Can you share it?

**Comment by averyzhong** [comment] 2020-09-08 03:32
Have you solved this problem? I also want to run the emulator on the ARM server. Are you running now? If it is running, can you share how you did it?

**Comment by copiltembel** [comment] 2020-09-08 06:59
@averyzhong Unfortunately not. I couldn't find any newer images. But [building the AOSP from source](https://source.android.com/setup/build/building) seems like a good lead.

**Comment by averyzhong** [comment] 2020-09-24 13:58
> @averyzhong Unfortunately not. I couldn't find any newer images. But [building the AOSP from source](https://source.android.com/setup/build/building) seems like a good lead.

I compiled the image from AOSP myself, but it doesn't work, it doesn't start up, and I fall into a startup loop

**Comment by 741g** [comment] 2020-09-24 14:59
Hi @averyzhong, we found a recent regression in the guest arm64 kernel that makes it bootloop. Should be fixed soon.

**Comment by copiltembel** [comment] 2020-09-24 16:19
@741g Sounds great!

From what I saw in the AOSP, there are some "standard" arm64 emulator images provided in the default menu. When building one of those images, are they at the latest Android API level?
And is there some documentation on how to customize an Android image when targeting (the arm64) emulator?

Sorry if these questions are out of scope, but it's really hard to find this information elsewhere.

**Comment by averyzhong** [comment] 2020-09-25 02:22
@741g Sounds great, thanks for your answer.

**Comment by danielmalmq** [comment] 2021-03-02 21:41
New ARM system images has been released for the upcoming android version:
https://dl.google.com/android/repository/sys-img/google_apis/arm64-v8a-S_r01.zip
https://dl.google.com/android/repository/sys-img/google_apis_playstore/arm64-v8a-S_r01-linux.zip

Got the emulator to start them on an arm64 system, using emulator from https://ci.android.com/builds/submitted/7176368/aarch64_sdk_tools_linux/latest as long as some additional flags are set when starting the emulator "-qemu -cpu max -machine gic-version=max"

However the goldfish-webrtc-bridge is not included in the versions on ci.android.com and I am having issues with compiling the bridge. Specifically the protobuf files are not generated properly. 

@pokowaka any hints as to how to cross compile the goldfish-webrtc-bridge to aarch64

**Comment by pokowaka** [comment] 2021-03-03 00:51
That is going to be challenging. We are using a prebuilt for the webrtc libraries. Currently we have a prebuilt for:

- Windows msvc
- Linux x86_64
- Darwin x86_64

Creating a new prebuilt is going to be some work.  You will need to follow the steps here:

https://android.googlesource.com/platform/external/qemu/+/emu-master-dev/android/scripts/build-webrtc/

You might have to manually set a define in the headers:

The #define ABSL_OPTION_USE_STD_STRING_VIEW 0 was set to make sure that
absl didn't do any unexpected fallbacks.

**Comment by pokowaka** [comment] 2021-03-05 17:38
Turns out that we now have WebRTC in the android source tree. We are looking into seeing if we can build webrtc directly from source on our side.

I will keep you posted on any progress we make.

**Comment by danielmalmq** [comment] 2021-03-07 16:42
Awesome thanks!

**Comment by averyzhong** [comment] 2021-03-20 10:06
https://ci.android.com/builds/submitted/7176368/aarch64_sdk_tools_linux/latest 
https://ci.android.com/builds/submitted/7223358/sdk_arm64-sdk/latest

I downloaded the latest ARM emulator and ARM system images from the above URLs, but this error( Control message: Could not find 'android.hardware.media.omx@1.0::IOmxStore/default) occurs when I run emulator. Can someone help me? Thanks!

logs:
[  460.783018][    T1] init: Service 'credstore' (pid 2870) exited with status 0
[  460.783976][    T1] init: Sending signal 9 to service 'credstore' (pid 2870) process group...
[  460.785270][    T1] libprocessgroup: Successfully killed process cgroup uid 1076 pid 2870 in 0ms
[  460.786577][    T1] init: process with updatable components 'credstore' exited 4 times in 4 minutes
[  460.788354][    T1] init: processing action (sys.init.updatable_crashing=1) from (/system/etc/init/flags_health_check.rc:10)
[  460.789933][    T1] init: starting service 'exec 103 (/system/bin/flags_health_check UPDATABLE_CRASHING)'...
[  460.793424][    T1] init: SVC_EXEC service 'exec 103 (/system/bin/flags_health_check UPDATABLE_CRASHING)' pid 2871 (uid 1000 gid 1000+0 context default) started; waiting...
[  460.797441][  T230] type=1400 audit(1616262062.729:6747): avc: denied { open } for comm="flags_health_ch" path="/dev/__properties__/u:object_r:device_logging_prop:s0" dev="tmpfs" ino=123 scontext=u:r:flags_health_check:s0 tcontext=u:object_r:device_logging_prop:s0 tclass=file permissive=1
[  460.798476][ T2871] audit: audit_lost=6299 audit_rate_limit=5 audit_backlog_limit=64
[  460.800821][  T230] type=1400 audit(1616262062.729:6748): avc: denied { getattr } for comm="flags_health_ch" path="/dev/__properties__/u:object_r:device_logging_prop:s0" dev="tmpfs" ino=123 scontext=u:r:flags_health_check:s0 tcontext=u:object_r:device_logging_prop:s0 tclass=file permissive=1
[  460.801760][ T2871] audit: rate limit exceeded
[  460.805194][  T230] type=1400 audit(1616262062.729:6749): avc: denied { map } for comm="flags_health_ch" path="/dev/__properties__/u:object_r:device_logging_prop:s0" dev="tmpfs" ino=123 scontext=u:r:flags_health_check:s0 tcontext=u:object_r:device_logging_prop:s0 tclass=file permissive=1
[  460.806814][    T1] init: Service 'exec 103 (/system/bin/flags_health_check UPDATABLE_CRASHING)' (pid 2871) exited with status 0 waiting took 0.014000 seconds
[  460.809148][  T230] type=1400 audit(1616262062.729:6750): avc: denied { open } for comm="flags_health_ch" path="/dev/__properties__/u:object_r:traced_enabled_prop:s0" dev="tmpfs" ino=236 scontext=u:r:flags_health_check:s0 tcontext=u:object_r:traced_enabled_prop:s0 tclass=file permissive=1
[  460.811008][    T1] init: Sending signal 9 to service 'exec 103 (/system/bin/flags_health_check UPDATABLE_CRASHING)' (pid 2871) process group...
[  460.814374][  T230] type=1400 audit(1616262062.729:6751): avc: denied { getattr } for comm="flags_health_ch" path="/dev/__properties__/u:object_r:traced_enabled_prop:s0" dev="tmpfs" ino=236 scontext=u:r:flags_health_check:s0 tcontext=u:object_r:traced_enabled_prop:s0 tclass=file permissive=1
[  460.816149][    T1] libprocessgroup: Successfully killed process cgroup uid 1000 pid 2871 in 0ms
[  460.819306][  T230] type=1400 audit(1616262062.729:6752): avc: denied { map } for comm="flags_health_ch" path="/dev/__properties__/u:object_r:traced_enabled_prop:s0" dev="tmpfs" ino=236 scontext=u:r:flags_health_check:s0 tcontext=u:object_r:traced_enabled_prop:s0 tclass=file permissive=1
[  460.823822][  T230] type=1400 audit(1616262062.729:6753): avc: denied { open } for comm="flags_health_ch" path="/dev/__properties__/u:object_r:traced_lazy_prop:s0" dev="tmpfs" ino=237 scontext=u:r:flags_health_check:s0 tcontext=u:object_r:traced_lazy_prop:s0 tclass=file permissive=1
[  461.336232][    T1] init: Control message: Could not find 'android.hardware.media.omx@1.0::IOmxStore/default' for ctl.interface_start from pid: 223 (/system/bin/hwservicemanager)
[  462.336642][    T1] init: Control message: Could not find 'android.hardware.media.omx@1.0::IOmxStore/default' for ctl.interface_start from pid: 223 (/system/bin/hwservicemanager)
[  463.337037][    T1] init: Control message: Could not find 'android.hardware.media.omx@1.0::IOmxStore/default' for ctl.interface_start from pid: 223 (/system/bin/hwservicemanager)
[  464.337542][    T1] init: Control message: Could not find 'android.hardware.media.omx@1.0::IOmxStore/default' for ctl.interface_start from pid: 223 (/system/bin/hwservicemanager)
[  465.338101][    T1] init: Control message: Could not find 'android.hardware.media.omx@1.0::IOmxStore/default' for ctl.interface_start from pid: 223 (/system/bin/hwservicemanager)
[  465.771868][    T1] init: starting service 'credstore'...
[  465.785466][    T1] init: Service 'credstore' (pid 2877) exited with status 0
[  465.786451][    T1] init: Sending signal 9 to service 'credstore' (pid 2877) process group...
[  465.787628][    T1] libprocessgroup: Successfully killed process cgroup uid 1076 pid 2877 in 0ms
[  465.789015][    T1] init: process with updatable components 'credstore' exited 4 times in 4 minutes
[  465.790821][    T1] init: processing action (sys.init.updatable_crashing=1) from (/system/etc/init/flags_health_check.rc:10)
[  465.792498][    T1] init: starting service 'exec 104 (/system/bin/flags_health_check UPDATABLE_CRASHING)'...
[  465.795813][    T1] init: SVC_EXEC service 'exec 104 (/system/bin/flags_health_check UPDATABLE_CRASHING)' pid 2878 (uid 1000 gid 1000+0 context default) started; waiting...
[  465.800065][ T2878] audit: audit_lost=6316 audit_rate_limit=5 audit_backlog_limit=64
[  465.800088][  T230] type=1400 audit(1616262067.729:6771): avc: denied { open } for comm="flags_health_ch" path="/dev/__properties__/u:object_r:dynamic_system_prop:s0" dev="tmpfs" ino=128 scontext=u:r:flags_health_check:s0 tcontext=u:object_r:dynamic_system_prop:s0 tclass=file permissive=1
[  465.801084][ T2878] audit: rate limit exceeded
[  465.804417][  T230] type=1400 audit(1616262067.729:6772): avc: denied { getattr } for comm="flags_health_ch" path="/dev/__properties__/u:object_r:dynamic_system_prop:s0" dev="tmpfs" ino=128 scontext=u:r:flags_health_check:s0 tcontext=u:object_r:dynamic_system_prop:s0 tclass=file permissive=1
[  465.807010][    T1] init: Service 'exec 104 (/system/bin/flags_health_check UPDATABLE_CRASHING)' (pid 2878) exited with status 0 waiting took 0.012000 seconds
[  465.808361][  T230] type=1400 audit(1616262067.729:6773): avc: denied { map } for comm="flags_health_ch" path="/dev/__properties__/u:object_r:dynamic_system_prop:s0" dev="tmpfs" ino=128 scontext=u:r:flags_health_check:s0 tcontext=u:object_r:dynamic_system_prop:s0 tclass=file permissive=1
[  465.810154][    T1] init: Sending signal 9 to service 'exec 104 (/system/bin/flags_health_check UPDATABLE_CRASHING)' (pid 2878) process group...
[  465.813524][  T230] type=1400 audit(1616262067.733:6774): avc: denied { open } for comm="flags_health_ch" path="/dev/__properties__/u:object_r:exported_bluetooth_prop:s0" dev="tmpfs" ino=130 scontext=u:r:flags_health_check:s0 tcontext=u:object_r:exported_bluetooth_prop:s0 tclass=file permissive=1
[  465.815259][    T1] libprocessgroup: Successfully killed process cgroup uid 1000 pid 2878 in 0ms
[  465.818663][  T230] type=1400 audit(1616262067.733:6775): avc: denied { getattr } for comm="flags_health_ch" path="/dev/__properties__/u:object_r:exported_bluetooth_prop:s0" dev="tmpfs" ino=130 scontext=u:r:flags_health_check:s0 tcontext=u:object_r:exported_bluetooth_prop:s0 tclass=file permissive=1
[  466.338516][    T1] init: Control message: Could not find 'android.hardware.media.omx@1.0::IOmxStore/default' for ctl.interface_start from pid: 223 (/system/bin/hwservicemanager)
[  467.338909][    T1] init: Control message: Could not find 'android.hardware.media.omx@1.0::IOmxStore/default' for ctl.interface_start from pid: 223 (/system/bin/hwservicemanager)
[  468.339312][    T1] init: Control message: Could not find 'android.hardware.media.omx@1.0::IOmxStore/default' for ctl.interface_start from pid: 223 (/system/bin/hwservicemanager)
[  469.339708][    T1] init: Control message: Could not find 'android.hardware.media.omx@1.0::IOmxStore/default' for ctl.interface_start from pid: 223 (/system/bin/hwservicemanager)
[  470.340312][    T1] init: Control message: Could not find 'android.hardware.media.omx@1.0::IOmxStore/default' for ctl.interface_start from pid: 223 (/system/bin/hwservicemanager)
[  470.775045][    T1] init: starting service 'credstore'...
[  470.788766][    T1] init: Service 'credstore' (pid 2890) exited with status 0
[  470.789725][    T1] init: Sending signal 9 to service 'credstore' (pid 2890) process group...
[  470.790895][    T1] libprocessgroup: Successfully killed process cgroup uid 1076 pid 2890 in 0ms
[  470.792246][    T1] init: process with updatable components 'credstore' exited 4 times in 4 minutes
[  470.794083][    T1] init: processing action (sys.init.updatable_crashing=1) from (/system/etc/init/flags_health_check.rc:10)
[  470.795653][    T1] init: starting service 'exec 105 (/system/bin/flags_health_check UPDATABLE_CRASHING)'...
[  470.799010][    T1] init: SVC_EXEC service 'exec 105 (/system/bin/flags_health_check UPDATABLE_CRASHING)' pid 2891 (uid 1000 gid 1000+0 context default) started; waiting...
[  470.803088][ T2891] audit: audit_lost=6326 audit_rate_limit=5 audit_backlog_limit=64
[  470.803103][  T230] type=1400 audit(1616262072.733:6786): avc: denied { open } for comm="flags_health_ch" path="/dev/__properties__/u:object_r:drm_service_config_prop:s0" dev="tmpfs" ino=125 scontext=u:r:flags_health_check:s0 tcontext=u:object_r:drm_service_config_prop:s0 tclass=file permissive=1
[  470.804120][ T2891] audit: rate limit exceeded

**Comment by bipindr123** [comment] 2021-06-04 17:59
> New ARM system images has been released for the upcoming android version:
> https://dl.google.com/android/repository/sys-img/google_apis/arm64-v8a-S_r01.zip
> https://dl.google.com/android/repository/sys-img/google_apis_playstore/arm64-v8a-S_r01-linux.zip
> 
> Got the emulator to start them on an arm64 system, using emulator from https://ci.android.com/builds/submitted/7176368/aarch64_sdk_tools_linux/latest as long as some additional flags are set when starting the emulator "-qemu -cpu max -machine gic-version=max"
> 
> However the goldfish-webrtc-bridge is not included in the versions on ci.android.com and I am having issues with compiling the bridge. Specifically the protobuf files are not generated properly.
> 
> @pokowaka any hints as to how to cross compile the goldfish-webrtc-bridge to aarch64

how were you able to create the avd? 
I get this
Warning: Failed to find package 'emulator'
my emulator files are placed in /home/ubuntu/AndroidSDK/emulator and avd manager in /home/ubuntu/AndroidSDK/cmdline-tools/latest/bin
I have added emulator to path

**Comment by pokowaka** [comment] 2021-06-05 14:48
A few notes:

- We usually cross compile from linux-using gcc to target linux-aarch64. This should resolve your protobuf issues as we use x86 for protobuf generation.
- We now compile WebRTC from source, you have to pass the cmake_option WEBRTC=TRUE to the build configuration. (i.e. `./android/rebuild.sh --cmake_option WEBRTC=TRUE --target linux_aarch64`). We do not (yet) support Mac M1.
- We have never tested webrtc on linux arm, if it does not work we might have to figure out why (hopefully the build succeeds)
- Make sure your arm machine has the right dependencies in place: (see `android/scripts/aarch64-linux/launcher/setupdeps.sh`)

The majority of the webrtc build is auto generated, and you will not be able to update WebRTC it as it relies on internal google infrastructure. If you need patches from newer webrtc versions reach out and we can regen them for you.

**Comment by danielmalmq** [comment] 2021-06-07 14:48
Thanks I tested the latest develop branch and there are some more issues when compiling against aarch64. Passing the option `--cmake_option WEBRTC=TRUE` does not include the webrtc for some reason, so modifying the CMakeLists.txt to set WEBRTC from FALSE to TRUE given AARCH64 target.  

There are some more issues when building for ARM
webrtc/third_party/libyuv/source/scale_neon64.cc - assembly code won't compile but implementing the suggestions fixes it.
webrtc/third_party/libaom/source/config/config/ - is not populated correctly, manually copying the arm64 config files resolves it.
webrtc/modules/audio_processing/aec3/reverb_model_estimator.h - add memory.h
webrtc/third_party/pffft/pffft_unittest.cc - clear out main content of the test

Eventually it fails with undefined references to stuff
```
/usr/lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: archives/libwebrtc_common_audio_common_audio_c.a(spl_init.c.o):(.data.rel.ro+0x8): undefined reference to `WebRtcSpl_DownsampleFastNeon'
/usr/lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: archives/libwebrtc_common_audio_common_audio_c.a(spl_init.c.o):(.data.rel.ro+0x10): undefined reference to `WebRtcSpl_CrossCorrelationNeon'
/usr/lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: archives/libwebrtc_common_audio_common_audio_c.a(spl_init.c.o):(.data.rel.ro+0x18): undefined reference to `WebRtcSpl_MinValueW32Neon'
/usr/lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: archives/libwebrtc_common_audio_common_audio_c.a(spl_init.c.o):(.data.rel.ro+0x20): undefined reference to `WebRtcSpl_MinValueW16Neon'
/usr/lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: archives/libwebrtc_common_audio_common_audio_c.a(spl_init.c.o):(.data.rel.ro+0x28): undefined reference to `WebRtcSpl_MaxValueW32Neon'
/usr/lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: archives/libwebrtc_common_audio_common_audio_c.a(spl_init.c.o):(.data.rel.ro+0x30): undefined reference to `WebRtcSpl_MaxValueW16Neon'
/usr/lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: archives/libwebrtc_common_audio_common_audio_c.a(spl_init.c.o):(.data.rel.ro+0x38): undefined reference to `WebRtcSpl_MaxAbsValueW32Neon'
/usr/lib/gcc-cross/aarch64-linux-gnu/9/../../../../aarch64-linux-gnu/bin/ld: archives/libwebrtc_common_audio_common_audio_c.a(spl_init.c.o):(.data.rel.ro+0x40): undefined reference to `WebRtcSpl_MaxAbsValueW16Neon
```

**Comment by pokowaka** [comment] 2021-06-22 12:08
Let me see if merging down newer versions of WebRTC can fix this.  I've filled a ticket with Google so it is easier to get others involved if needed:

[b/191745658](https://issuetracker.google.com/issues/191745658)

**Comment by prapti02** [comment] 2021-06-23 04:31
> New ARM system images has been released for the upcoming android version:
> https://dl.google.com/android/repository/sys-img/google_apis/arm64-v8a-S_r01.zip
> https://dl.google.com/android/repository/sys-img/google_apis_playstore/arm64-v8a-S_r01-linux.zip
> 
> Got the emulator to start them on an arm64 system, using emulator from https://ci.android.com/builds/submitted/7176368/aarch64_sdk_tools_linux/latest as long as some additional flags are set when starting the emulator "-qemu -cpu max -machine gic-version=max"
> 
> However the goldfish-webrtc-bridge is not included in the versions on ci.android.com and I am having issues with compiling the bridge. Specifically the protobuf files are not generated properly.
> 
> @pokowaka any hints as to how to cross compile the goldfish-webrtc-bridge to aarch64

Hi Daniel,
I am trying to implement your method on a x86_64 processor using qemu. But, I am having trouble running the emulator. Could you share your email address, so that I can send the issue? 

Thank you!

**Comment by danielmalmq** [comment] 2021-06-23 07:15
> > New ARM system images has been released for the upcoming android version:
> > https://dl.google.com/android/repository/sys-img/google_apis/arm64-v8a-S_r01.zip
> > https://dl.google.com/android/repository/sys-img/google_apis_playstore/arm64-v8a-S_r01-linux.zip
> > Got the emulator to start them on an arm64 system, using emulator from https://ci.android.com/builds/submitted/7176368/aarch64_sdk_tools_linux/latest as long as some additional flags are set when starting the emulator "-qemu -cpu max -machine gic-version=max"
> > However the goldfish-webrtc-bridge is not included in the versions on ci.android.com and I am having issues with compiling the bridge. Specifically the protobuf files are not generated properly.
> > @pokowaka any hints as to how to cross compile the goldfish-webrtc-bridge to aarch64
> 
> Hi Daniel,
> I am trying to implement your method on a x86_64 processor using qemu. But, I am having trouble running the emulator. Could you share your email address, so that I can send the issue?
> 
> Thank you!

Yeah sure, ping me on daniel.miip@gmail.com and I will contact you with my real account

**Comment by pokowaka** [comment] 2021-06-23 11:57
Quick update, it looks like there is an issue in the WebRTC build that needs to be addressed. I'm going to put a temporary workaround in place if possible.

**Comment by pokowaka** [comment] 2021-06-23 13:00
CL is out: https://android-review.googlesource.com/c/platform/external/webrtc/+/1744453

**Comment by pokowaka** [comment] 2021-06-30 12:21
Initial version of arm webrtc has been merged with https://ci.android.com/builds/branches/aosp-emu-master-dev/grid?head=7508155&tail=7508155.

**Comment by danielmalmq** [comment] 2021-07-05 06:19
@pokowaka Awesome work! I tested building the arm version of the webrtc bridge over the weekend and it compiles nicely and runs just as nicely :)

**Comment by Sandeepa-B** [comment] 2021-07-15 15:06
> 
> 
> New ARM system images has been released for the upcoming android version:
> https://dl.google.com/android/repository/sys-img/google_apis/arm64-v8a-S_r01.zip
> https://dl.google.com/android/repository/sys-img/google_apis_playstore/arm64-v8a-S_r01-linux.zip
> 
> Got the emulator to start them on an arm64 system, using emulator from https://ci.android.com/builds/submitted/7176368/aarch64_sdk_tools_linux/latest as long as some additional flags are set when starting the emulator "-qemu -cpu max -machine gic-version=max"
> 
> However the goldfish-webrtc-bridge is not included in the versions on ci.android.com and I am having issues with compiling the bridge. Specifically the protobuf files are not generated properly.
> 
> @pokowaka any hints as to how to cross compile the goldfish-webrtc-bridge to aarch64

 @danielmalmq,  Could you please let us know on which arm64 machine were you able to start this emulator successfully ?

Thanks!

**Comment by danielmalmq** [comment] 2021-07-22 20:07
> > New ARM system images has been released for the upcoming android version:
> > https://dl.google.com/android/repository/sys-img/google_apis/arm64-v8a-S_r01.zip
> > https://dl.google.com/android/repository/sys-img/google_apis_playstore/arm64-v8a-S_r01-linux.zip
> > Got the emulator to start them on an arm64 system, using emulator from https://ci.android.com/builds/submitted/7176368/aarch64_sdk_tools_linux/latest as long as some additional flags are set when starting the emulator "-qemu -cpu max -machine gic-version=max"
> > However the goldfish-webrtc-bridge is not included in the versions on ci.android.com and I am having issues with compiling the bridge. Specifically the protobuf files are not generated properly.
> > @pokowaka any hints as to how to cross compile the goldfish-webrtc-bridge to aarch64
> 
> @danielmalmq, Could you please let us know on which arm64 machine were you able to start this emulator successfully ?
> 
> Thanks!

@Sandeepa-B Hey sure thing. I have it running on an aws ec2 c6g.metal running 20.04.

**Closed** 2021-08-25 16:44 UTC

**Comment by adiantek** [comment] 2021-11-05 01:39
@danielmalmq  doesn't work your solution for me:
![image](https://user-images.githubusercontent.com/13407885/140443308-e9ac1a1e-5edc-4058-aa46-e40280c63e0d.png)
I don't know even how to debug it. I downloaded cmdline-tools on x86_64,


sdk-repo-linux_aarch64-emulator-7176368.zip on branch aosp-emu-master-dev on target aarch64_sdk_tools_linux at 7176368
```
  Path                                                      | Version | Description                         | Location
  -------                                                   | ------- | -------                             | -------
  emulator                                                  | 30.9.5  | Android Emulator                    | emulator-mixed
  patcher;v4                                                | 1       | SDK Patch Applier v4                | patcher/v4
  platform-tools                                            | 31.0.3  | Android SDK Platform-Tools          | platform-tools
  platforms;android-Sv2                                     | 1       | Android SDK Platform Sv2            | platforms/android-Sv2
  system-images;android-S;google_apis_playstore;arm64-v8a   | 1       | Google Play ARM 64 v8a System Image | system-images/android-Sv2/google_apis/arm64-v8a
  system-images;android-Sv2;google_apis_playstore;arm64-v8a | 1       | Google Play ARM 64 v8a System Image | system-images/android-Sv2/google_apis_playstore/arm64-v8a
```
Then I downloaded `sdk-repo-linux_aarch64-emulator-7176368.zip on branch aosp-emu-master-dev on target aarch64_sdk_tools_linux at 7176368`, moved emulator to emulator-mixed, unpacked ZIP. I installed your apt-get, copied your command and have black screen.  The same problem I've on x86_64, but I thought it's due to poor CPU.

**Comment by s1ri1337** [comment] 2021-12-04 07:21
> > > New ARM system images has been released for the upcoming android version:
> > > https://dl.google.com/android/repository/sys-img/google_apis/arm64-v8a-S_r01.zip
> > > https://dl.google.com/android/repository/sys-img/google_apis_playstore/arm64-v8a-S_r01-linux.zip
> > > Got the emulator to start them on an arm64 system, using emulator from https://ci.android.com/builds/submitted/7176368/aarch64_sdk_tools_linux/latest as long as some additional flags are set when starting the emulator "-qemu -cpu max -machine gic-version=max"
> > > However the goldfish-webrtc-bridge is not included in the versions on ci.android.com and I am having issues with compiling the bridge. Specifically the protobuf files are not generated properly.
> > > @pokowaka any hints as to how to cross compile the goldfish-webrtc-bridge to aarch64
> > 
> > 
> > @danielmalmq, Could you please let us know on which arm64 machine were you able to start this emulator successfully ?
> > Thanks!
> 
> @Sandeepa-B Hey sure thing. I have it running on an aws ec2 c6g.metal running ubuntu 20.04.
> 
> Crosscompile the emulator on an x86_64 machine targeting aarch64. Then transfer the compiled binaries to your arm machine.
> 
> Install all the required stuff with something like
> 
> `sudo apt-get install -y --no-install-recommends libgl1-mesa-dev libglu1-mesa-dev freeglut3-dev g++-aarch64-linux-gnu gcc-aarch64-linux-gnu git build-essential python qemu-kvm ninja-build ccache libgl1-mesa-glx lz4 libc6 adb unzip xcb xfce4 xfce4-goodies tree libpcre2-16-0 cpu-checker qemu-kvm`
> 
> To view it over vnc I used tightvncserver `sudo apt install ubuntu-desktop tightvncserver gnome-panel gnome-settings-daemon metacity nautilus gnome-terminal`
> 
> Then I set the ANDROID_SDK_ROOT dir to ~/Android/Sdk here I create the two folders `platforms` and `platform-tools` else the emulator will terminate prematurely. I also place the emulator here.
> 
> Fetch the latest arm image from https://dl.google.com/android/repository/sys-img/google_apis/arm64-v8a-S_r05.zip and extract it to ANDROID_SDK_ROOT/system-images/arm64-v8a
> 
> Create an avd config manually and set the config to something like:
> 
> ```
> image.sysdir.1=system-images/arm64-v8a
> AvdId=Pixel2
> PlayStore.enabled=false
> abi.type=arm64-v8a
> avd.ini.displayname=Pixel2
> avd.ini.encoding=UTF-8
> disk.dataPartition.size=800M
> fastboot.chosenSnapshotFile=
> fastboot.forceChosenSnapshotBoot=no
> fastboot.forceColdBoot=no
> fastboot.forceFastBoot=yes
> hw.accelerometer=yes
> hw.arc=false
> hw.audioInput=yes
> hw.battery=yes
> hw.camera.back=virtualscene
> hw.camera.front=emulated
> hw.cpu.arch=arm64
> hw.cpu.ncore=2
> hw.dPad=no
> hw.device.hash2=MD5:7261a27397b516f863a19379952d8fa4
> hw.device.manufacturer=User
> hw.device.name=Pixel2
> hw.gps=yes
> hw.gpu.enabled=yes
> hw.gpu.mode=auto
> hw.initialOrientation=Portrait
> hw.keyboard=yes
> hw.lcd.density=160
> hw.lcd.height=768
> hw.lcd.width=432
> hw.mainKeys=no
> hw.ramSize=1536
> hw.sdCard=yes
> hw.sensors.orientation=yes
> hw.sensors.proximity=yes
> hw.trackBall=no
> runtime.network.latency=none
> runtime.network.speed=full
> showDeviceFrame=no
> skin.dynamic=yes
> skin.name=432x768
> skin.path=_no_skin
> skin.path.backup=_no_skin
> tag.display=Google APIs
> tag.id=google_apis
> vm.heapSize=48
> ```
> 
> Then it should start when you issue `~/Android/Sdk/emulator/emulator @Pixel2 -verbose -gpu swiftshader_indirect -grpc 8554 -skip-adb-auth -shell-serial file:1.txt -qemu -cpu max -machine gic-version=max`
> 
> And tag on -no-window when not using vnc
> 
> If you have issues with vulkan not working as intended turn it off by adding `Vulkan = off` to `~/.android/advancedFeatures.ini`

Hi,
Do you think this is possible for ARM 32 bit devices? Any help would be appreciated.

**Comment by victorccaldas** [comment] 2022-08-23 05:10
> > > New ARM system images has been released for the upcoming android version:
> 
> > > https://dl.google.com/android/repository/sys-img/google_apis/arm64-v8a-S_r01.zip
> 
> > > https://dl.google.com/android/repository/sys-img/google_apis_playstore/arm64-v8a-S_r01-linux.zip
> 
> > > Got the emulator to start them on an arm64 system, using emulator from https://ci.android.com/builds/submitted/7176368/aarch64_sdk_tools_linux/latest as long as some additional flags are set when starting the emulator "-qemu -cpu max -machine gic-version=max"
> 
> > > However the goldfish-webrtc-bridge is not included in the versions on ci.android.com and I am having issues with compiling the bridge. Specifically the protobuf files are not generated properly.
> 
> > > @pokowaka any hints as to how to cross compile the goldfish-webrtc-bridge to aarch64
> 
> > 
> 
> > @danielmalmq, Could you please let us know on which arm64 machine were you able to start this emulator successfully ?
> 
> > 
> 
> > Thanks!
> 
> 
> 
> @Sandeepa-B Hey sure thing. I have it running on an aws ec2 c6g.metal running ubuntu 20.04.
> 
> 
> 
> Crosscompile the emulator on an x86_64 machine targeting aarch64. Then transfer the compiled binaries to your arm machine.
> 
> 
> 
> Install all the required stuff with something like
> 
> 
> 
> `sudo apt-get install -y --no-install-recommends libgl1-mesa-dev libglu1-mesa-dev freeglut3-dev g++-aarch64-linux-gnu gcc-aarch64-linux-gnu git build-essential python qemu-kvm ninja-build ccache libgl1-mesa-glx lz4 libc6 adb unzip xcb xfce4 xfce4-goodies tree libpcre2-16-0 cpu-checker qemu-kvm`
> 
> 
> 
> To view it over vnc I used tightvncserver
> 
> `sudo apt install ubuntu-desktop tightvncserver gnome-panel gnome-settings-daemon metacity nautilus gnome-terminal`
> 
> 
> 
> Then I set the ANDROID_SDK_ROOT dir to ~/Android/Sdk here I create the two folders `platforms` and `platform-tools` else the emulator will terminate prematurely. I also place the emulator here.
> 
> 
> 
> Fetch the latest arm image from https://dl.google.com/android/repository/sys-img/google_apis/arm64-v8a-S_r05.zip and extract it to ANDROID_SDK_ROOT/system-images/arm64-v8a
> 
> 
> 
> Create an avd config manually and set the config to something like:
> 
> ```
> 
> image.sysdir.1=system-images/arm64-v8a
> 
> AvdId=Pixel2
> 
> PlayStore.enabled=false
> 
> abi.type=arm64-v8a
> 
> avd.ini.displayname=Pixel2
> 
> avd.ini.encoding=UTF-8
> 
> disk.dataPartition.size=800M
> 
> fastboot.chosenSnapshotFile=
> 
> fastboot.forceChosenSnapshotBoot=no
> 
> fastboot.forceColdBoot=no
> 
> fastboot.forceFastBoot=yes
> 
> hw.accelerometer=yes
> 
> hw.arc=false
> 
> hw.audioInput=yes
> 
> hw.battery=yes
> 
> hw.camera.back=virtualscene
> 
> hw.camera.front=emulated
> 
> hw.cpu.arch=arm64
> 
> hw.cpu.ncore=2
> 
> hw.dPad=no
> 
> hw.device.hash2=MD5:7261a27397b516f863a19379952d8fa4
> 
> hw.device.manufacturer=User
> 
> hw.device.name=Pixel2
> 
> hw.gps=yes
> 
> hw.gpu.enabled=yes
> 
> hw.gpu.mode=auto
> 
> hw.initialOrientation=Portrait
> 
> hw.keyboard=yes
> 
> hw.lcd.density=160
> 
> hw.lcd.height=768
> 
> hw.lcd.width=432
> 
> hw.mainKeys=no
> 
> hw.ramSize=1536
> 
> hw.sdCard=yes
> 
> hw.sensors.orientation=yes
> 
> hw.sensors.proximity=yes
> 
> hw.trackBall=no
> 
> runtime.network.latency=none
> 
> runtime.network.speed=full
> 
> showDeviceFrame=no
> 
> skin.dynamic=yes
> 
> skin.name=432x768
> 
> skin.path=_no_skin
> 
> skin.path.backup=_no_skin
> 
> tag.display=Google APIs
> 
> tag.id=google_apis
> 
> vm.heapSize=48
> 
> ```
> 
> 
> 
> Then it should start when you issue 
> 
> `~/Android/Sdk/emulator/emulator @Pixel2 -verbose -gpu swiftshader_indirect -grpc 8554 -skip-adb-auth  -shell-serial file:1.txt -qemu -cpu max -machine gic-version=max`
> 
> 
> 
> And tag on -no-window when not using vnc
> 
> 
> 
> If you have issues with vulkan not working as intended turn it off by adding `Vulkan = off` to `~/.android/advancedFeatures.ini`

Is it possible to do all this in a simpler, non-pro manner? Wish I could understand all you did there. But I need a cheap way of accessing android on cloud
